# Generated by Django 3.2.6 on 2022-02-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAdminShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percentage', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Delivery Admin Share',
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accounts/payment_proof')),
            ],
            options={
                'verbose_name_plural': 'Payment Proof',
            },
        ),
        migrations.CreateModel(
            name='ShopAdminShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percentage', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Shop Admin Share',
            },
        ),
        migrations.CreateModel(
            name='ShopkeperPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.order')),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.paymentproof')),
            ],
            options={
                'verbose_name_plural': 'Shopkeeper Payment',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPersonPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.order')),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.paymentproof')),
            ],
            options={
                'verbose_name_plural': 'Delivery Person Payment',
            },
        ),
    ]
