# Generated by Django 3.2.6 on 2022-03-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Candidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('male_side_agree', models.BooleanField()),
                ('female_side_agree', models.BooleanField()),
                ('active', models.BooleanField()),
                ('processed', models.BooleanField()),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='female', to='Candidate.candidates')),
                ('male', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='male', to='Candidate.candidates')),
            ],
            options={
                'verbose_name_plural': 'Match',
            },
        ),
    ]
