# Generated by Django 3.2.6 on 2022-02-28 03:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Requirments', '0001_initial'),
        ('RegSchool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('teacher', models.IntegerField()),
                ('limit', models.CharField(max_length=2)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requirments.classes')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegSchool.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requirments.session')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClassStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=250)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='class/pictures/')),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacherclass')),
            ],
        ),
    ]
