# Generated by Django 3.2.6 on 2022-02-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compulsory', models.IntegerField()),
                ('per_km', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Delivery Charge',
            },
        ),
    ]
