# Generated by Django 3.2.6 on 2022-02-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Requirments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('checker', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requirments.classsubjects')),
            ],
        ),
    ]
