# Generated by Django 3.2.6 on 2022-02-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Requirments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(null=True)),
                ('therefor', models.CharField(choices=[('S', 'Self-Paced'), ('O', 'Online-School')], max_length=20)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requirments.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.content')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.module'),
        ),
        migrations.AddField(
            model_name='content',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requirments.subjects'),
        ),
    ]
