# Generated by Django 3.2.6 on 2022-02-28 05:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('first_name', models.CharField(max_length=250)),
                ('address', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('city', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
