# Generated by Django 3.2.6 on 2022-03-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_order_user'),
        ('Delivery', '0005_alter_deliverytasks_task_to'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
