# Generated by Django 3.2.6 on 2022-03-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPicture',
        ),
    ]
