# Generated by Django 3.2.6 on 2022-02-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('user', models.IntegerField()),
            ],
        ),
    ]
