# Generated by Django 3.2.6 on 2022-03-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='relationships/candidate')),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('occupation', models.CharField(blank=True, choices=[('None', 'None'), ('Job', 'Job'), ('Business', 'Business')], max_length=200, null=True)),
                ('education', models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Matric', 'Matric'), ('Inter', 'Inter'), ('Graduation', 'Graduation'), ('Masters', 'Masters'), ('PHD', 'PHD')], max_length=200, null=True)),
                ('living_status', models.CharField(blank=True, choices=[('With Family', 'With Family'), ('Rent', 'Rent'), ('Persional', 'Persional')], max_length=200, null=True)),
                ('cast', models.CharField(blank=True, max_length=50, null=True)),
                ('siblings', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mobile', models.BigIntegerField()),
                ('address', models.CharField(max_length=250)),
                ('cnic', models.BigIntegerField()),
                ('place_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Married-Twice', 'Married-Twice'), ('Divorced', 'Divorced'), ('Divorced-Twice', 'Divorced-Twice')], max_length=200)),
                ('parents', models.CharField(choices=[('Alive', 'Alive'), ('Mother-Only', 'Mother-Only'), ('Father-Only', 'Father-Only'), ('Passed', 'Passed')], max_length=200)),
                ('discription', models.CharField(blank=True, max_length=500, null=True)),
                ('father_occupation', models.CharField(blank=True, choices=[('None', 'None'), ('Job', 'Job'), ('Business', 'Business')], max_length=200, null=True)),
                ('facebook_id', models.URLField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('religion', models.CharField(choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Cristian', 'Cristian'), ('Other', 'Other')], max_length=200)),
                ('mother_toungue', models.CharField(max_length=50)),
                ('monthly_income', models.IntegerField(blank=True, null=True)),
                ('matched', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Candidates',
            },
        ),
    ]
