# Generated by Django 3.2.6 on 2022-03-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_orderreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreview',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
