# Generated by Django 3.2.6 on 2022-03-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_auto_20220309_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreview',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
