# Generated by Django 3.2.6 on 2022-03-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blogtags_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogTags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
