# Generated by Django 3.2.6 on 2022-03-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_blog_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
