# Generated by Django 3.2.6 on 2022-02-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Requirments', '0001_initial'),
        ('RegSchool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indivisuals',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('user', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('fees', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requirments.classes')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegSchool.school')),
            ],
        ),
    ]
