# Generated by Django 3.2.6 on 2022-02-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Requirments', '0001_initial'),
        ('Indivisuals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indivisuals',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Requirments.session'),
            preserve_default=False,
        ),
    ]
