# Generated by Django 3.2.6 on 2022-02-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Indivisuals', '0002_indivisuals_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indivisuals',
            name='session',
        ),
    ]
