# Generated by Django 3.2.6 on 2022-02-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswers',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='exam/papers/answers/')),
                ('checker', models.IntegerField()),
                ('checked', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=250)),
                ('marks', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamStatus',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('exam_number', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsChecked',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('checker', models.IntegerField()),
                ('obtained', models.IntegerField()),
            ],
        ),
    ]
