# Generated by Django 3.2.6 on 2022-02-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Indivisuals', '0001_initial'),
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionschecked',
            name='indi_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Indivisuals.indivisuals'),
        ),
        migrations.AddField(
            model_name='questionschecked',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.examquestions'),
        ),
    ]
