# Generated by Django 3.2.6 on 2022-02-28 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Indivisuals', '0001_initial'),
        ('Exam', '0002_initial'),
        ('Requirments', '0001_initial'),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionschecked',
            name='teach_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacherclassstudents'),
        ),
        migrations.AddField(
            model_name='guide',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requirments.subjects'),
        ),
        migrations.AddField(
            model_name='examstatus',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requirments.classes'),
        ),
        migrations.AddField(
            model_name='examstatus',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requirments.session'),
        ),
        migrations.AddField(
            model_name='examstatus',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requirments.subjects'),
        ),
        migrations.AddField(
            model_name='examquestions',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.examstatus'),
        ),
        migrations.AddField(
            model_name='examanswers',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.examstatus'),
        ),
        migrations.AddField(
            model_name='examanswers',
            name='indi_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Indivisuals.indivisuals'),
        ),
        migrations.AddField(
            model_name='examanswers',
            name='teach_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacherclassstudents'),
        ),
    ]
