# Generated by Django 3.2.6 on 2022-03-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20220306_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bank_account',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='userdata',
            name='easypaisa',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='userdata',
            name='mobile',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='nic',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
