# Generated by Django 3.2.6 on 2022-03-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20220306_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
