# Generated by Django 3.2.6 on 2022-03-06 07:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_userdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
