# Generated by Django 3.2.6 on 2022-02-28 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.IntegerField()),
                ('class_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('session_number', models.IntegerField()),
                ('session_start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.CharField(max_length=50)),
                ('visits', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassSubjects',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requirments.classes')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Requirments.subjects')),
            ],
        ),
    ]
