# Generated by Django 3.2.6 on 2022-02-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shop', '0001_initial'),
        ('Customer', '0001_initial'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('active', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=11)),
                ('nic', models.CharField(max_length=15)),
                ('bank_account', models.CharField(blank=True, max_length=24)),
                ('easypaisa', models.CharField(blank=True, max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Delivery Person',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.order')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.deliveryperson')),
                ('task_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.shops')),
                ('task_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.userdata')),
            ],
            options={
                'verbose_name_plural': 'Delivery Task',
            },
        ),
        migrations.CreateModel(
            name='DeliveryProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/delivery_proof')),
                ('date', models.DateField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.order')),
            ],
            options={
                'verbose_name_plural': 'Delivery Proof',
            },
        ),
    ]
