# Generated by Django 3.2.6 on 2022-02-28 12:47

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='area',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0, srid=4326), geography=True, srid=4326),
        ),
    ]
