# Generated by Django 3.2.6 on 2022-03-01 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_deliveryperson_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytasks',
            name='drop',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverytasks',
            name='pick',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverytasks',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
