# Generated by Django 3.2.6 on 2022-03-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_auto_20220301_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytasks',
            name='drop',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverytasks',
            name='pick',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
