# Generated by Django 3.2.6 on 2022-03-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0005_alter_deliverytasks_task_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='easypaisa',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deliveryperson',
            name='nic',
        ),
    ]
