# Generated by Django 3.2.6 on 2022-03-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0006_auto_20220306_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='bank_account',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='easypaisa',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='mobile',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='name',
            field=models.CharField(default='Tabish', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='nic',
            field=models.CharField(default=374637846827, max_length=15),
            preserve_default=False,
        ),
    ]
