# Generated by Django 3.2.6 on 2022-02-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=5000)),
                ('image', models.FileField(blank=True, null=True, upload_to='blogs/post/')),
                ('video', models.URLField(blank=True, null=True)),
                ('sound', models.FileField(blank=True, null=True, upload_to='blogs/post/')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='ReactTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('icon', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'React Types',
            },
        ),
        migrations.CreateModel(
            name='PostReact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.post')),
                ('react', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.reacttypes')),
            ],
            options={
                'verbose_name_plural': 'Post Reacts',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('comment', models.CharField(max_length=250)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.post')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
