# Generated by Django 3.2.6 on 2022-03-02 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_posttags_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreact',
            options={'verbose_name_plural': 'Reacts'},
        ),
        migrations.AlterModelOptions(
            name='posttags',
            options={'verbose_name_plural': 'Post Tags'},
        ),
    ]
