# Generated by Django 3.2.6 on 2022-03-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20220302_0549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
