# Generated by Django 3.2.6 on 2022-03-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20220302_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='abc', upload_to='blogs/post/'),
            preserve_default=False,
        ),
    ]
