# Generated by Django 3.2.6 on 2022-03-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=50000),
        ),
    ]
