# Generated by Django 3.2.6 on 2022-03-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_auto_20220303_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reacttypes',
            name='points_add',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reacttypes',
            name='points_subtract',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
