# Generated by Django 3.2.6 on 2022-03-10 04:23

import Discussion.Questionare.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Questionare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Questions/', validators=[Discussion.Questionare.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='answer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Questions/', validators=[Discussion.Questionare.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Questions/', validators=[Discussion.Questionare.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Questions/', validators=[Discussion.Questionare.models.validate_file_size]),
        ),
    ]
