# Generated by Django 3.2.6 on 2022-03-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionare', '0003_auto_20220310_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Questionare.question'),
            preserve_default=False,
        ),
    ]
