# Generated by Django 3.2.6 on 2022-02-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0001_initial'),
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blog')),
            ],
            options={
                'verbose_name_plural': 'Bunches',
            },
        ),
        migrations.CreateModel(
            name='BunchPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bunch.bunch')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.post')),
            ],
            options={
                'verbose_name_plural': 'Bunch Posts',
            },
        ),
    ]
