# Generated by Django 3.2.6 on 2022-03-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunchpost',
            name='serial',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
